# Generated by Django 4.2.6 on 2023-10-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_album_user_band_user_song_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumReviewComment',
        ),
    ]
